### ISSUE TITLE
Example project not loading

### ISSUE THREAD

**Issue by markbao** [Elgatomontes/SwiftJavascriptBridge#4]
Installed pods through CocoaPods. Updated Podfile for CocoaPods 1.0:

``` rb
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!
xcodeproj 'SwiftJavascriptBridge'
use_frameworks!

target 'SwiftJavascriptBridge_Example' do
  pod "SwiftJavascriptBridge"
end

target 'SwiftJavascriptBridge_Tests' do
  pod "SwiftJavascriptBridge"
end
```

Error:

```
2016-07-18 21:41:43.233 SwiftJavascriptBridge_Example[79024:5791137] Unknown class _TtC29SwiftJavascriptBridge_Example14ViewController in Interface Builder file.
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithNoData() - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithStringData("Swift says: swiftCallWithStringData called.") - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithIntegerData("4") - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithDoubleData("8.327430000") - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithArrayData(["Swift says: swiftCallWithArrayData called.","Swift says: swiftCallWithArrayData called. (2)"]) - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithDictionaryData({"message":"Swift says: swiftCallWithDictionaryData called."}) - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
```

**Comment by GastonMontes** [comment]
Mark,

Thanks for reporting this problem.

I found that the Javascript example that was being used in the example is not online anymore.

I'm working to retrieve that file back.

Is the Bridge working correctly? did you test it?

Regards.

Gastón Montes.

De: Mark Bao notifications@github.com
Enviado: martes, 19 de julio de 2016 01:42 a.m.
Para: GastonMontes/SwiftJavascriptBridge
Asunto: [GastonMontes/SwiftJavascriptBridge] Example project not loading (#4)

Installed pods through CocoaPods.

Error:

2016-07-18 21:41:43.233 SwiftJavascriptBridge_Example[79024:5791137] Unknown class _TtC29SwiftJavascriptBridge_Example14ViewController in Interface Builder file.
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithNoData() - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithStringData("Swift says: swiftCallWithStringData called.") - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithIntegerData("4") - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithDoubleData("8.327430000") - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithArrayData(["Swift says: swiftCallWithArrayData called.","Swift says: swiftCallWithArrayData called. (2)"]) - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithDictionaryData({"message":"Swift says: swiftCallWithDictionaryData called."}) - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})

##

**Comment by GastonMontes** [comment]
Mark,

I just put the file online again and is working correctly.

Can you test the example project again to check that is working correctly for you?

Regards.

Gastón Montes.

---

De: Mark Bao notifications@github.com
Enviado: martes, 19 de julio de 2016 01:42 a.m.
Para: GastonMontes/SwiftJavascriptBridge
Asunto: [GastonMontes/SwiftJavascriptBridge] Example project not loading (#4)

Installed pods through CocoaPods.

Error:

2016-07-18 21:41:43.233 SwiftJavascriptBridge_Example[79024:5791137] Unknown class _TtC29SwiftJavascriptBridge_Example14ViewController in Interface Builder file.
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithNoData() - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithStringData("Swift says: swiftCallWithStringData called.") - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithIntegerData("4") - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithDoubleData("8.327430000") - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithArrayData(["Swift says: swiftCallWithArrayData called.","Swift says: swiftCallWithArrayData called. (2)"]) - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})
SwiftJavascriptBridge - EvaluateJavaScript Error: swiftCallWithDictionaryData({"message":"Swift says: swiftCallWithDictionaryData called."}) - Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={NSLocalizedDescription=A JavaScript exception occurred})

##
